---
## Reload system daemons or services
- name: Restart services for Debian 8 systems
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - uwsgi
    - nginx
    - postgresql

- name: Unzip MaxMind CSV
  unarchive:
    src: /tmp/GeoIPASNum2.zip
    dest: /tmp
    extra_opts: "-j"
    creates: /tmp/GeoIPASNum2.csv
    remote_src: yes