---
- hosts: all
  tasks:
    - include: update_pw_web.yml
      become: true
      become_user: root
- name: Fetch updated piecewise repo
  git: 
    repo: https://github.com/opentechinstitute/piecewise.git 
    dest: /opt/piecewise.git/
    version: master

- name: Deploy updated piecewise website code
  file:
    src: /opt/piecewise.git/piecewise_web
    dest: /opt/piecewise_web

- name: Restart services
  service: 
    name: "{{ item }}"
    state: restarted
  with_items: 
    - uwsgi
    - nginx
    