"""Create all tables.

Revision ID: 7cee758fd5b4
Revises: 
Create Date: 2019-12-20 21:48:00.877761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cee758fd5b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isp_user', sa.String(), nullable=True),
    sa.Column('other_isp', sa.String(), nullable=True),
    sa.Column('connection_type', sa.String(), nullable=True),
    sa.Column('cost_of_service', sa.String(), nullable=True),
    sa.Column('advertised_download', sa.Integer(), nullable=True),
    sa.Column('advertised_upload', sa.Integer(), nullable=True),
    sa.Column('actual_download', sa.Integer(), nullable=True),
    sa.Column('actual_upload', sa.Integer(), nullable=True),
    sa.Column('min_rtt', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(precision=64), nullable=True),
    sa.Column('longitude', sa.Float(precision=64), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_connection_type'), 'submission', ['connection_type'], unique=False)
    op.create_index(op.f('ix_submission_cost_of_service'), 'submission', ['cost_of_service'], unique=False)
    op.create_index(op.f('ix_submission_id'), 'submission', ['id'], unique=False)
    op.create_index(op.f('ix_submission_isp_user'), 'submission', ['isp_user'], unique=False)
    op.create_index(op.f('ix_submission_other_isp'), 'submission', ['other_isp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_other_isp'), table_name='submission')
    op.drop_index(op.f('ix_submission_isp_user'), table_name='submission')
    op.drop_index(op.f('ix_submission_id'), table_name='submission')
    op.drop_index(op.f('ix_submission_cost_of_service'), table_name='submission')
    op.drop_index(op.f('ix_submission_connection_type'), table_name='submission')
    op.drop_table('submission')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
